#!/bin/sh
# Copyright (C) 2004 International Business Machines Corporation and others.
# All Rights Reserved. This program and the accompanying
# materials are made available under the terms of the
# Common Public License v1.0 which accompanies this distribution.
#
# Author: Brian King <brking@us.ibm.com>
#
# iprinit
#
# System startup script for the ipr init facility
#
### BEGIN INIT INFO
# Provides: iprinit
# Required-Start:    $local_fs
# Should-Start:      $remote_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the ipr init daemon
# Description:       Start the ipr initialization daemon
### END INIT INFO

IPRINIT=/sbin/iprinit
test -x $IPRINIT || exit 5
. /lib/init/vars.sh
. /lib/lsb/init-functions

start() {
    if [ ! -d /sys/class/scsi_generic ] ; then
        modprobe sg
    fi
    start_daemon $IPRINIT --daemon
}

stop() {
    killproc $IPRINIT
}

status() {
    status_of_proc $IPRINIT iprinit
}

case "$1" in
    start)
	if init_is_upstart; then exit 1; fi
	[ "$VERBOSE" = no ] || log_daemon_msg "Starting ipr initialization daemon" iprinit
	start
	[ "$VERBOSE" = no ] || log_end_msg $?
	;;
    stop)
	if init_is_upstart; then exit 0; fi
	[ "$VERBOSE" = no ] || log_daemon_msg "Shutting down ipr initialization daemon" iprinit
	stop
	[ "$VERBOSE" = no ] || log_end_msg $?
	;;
    restart|reload|force-reload)
	if init_is_upstart; then exit 1; fi
	[ "$VERBOSE" = no ] || log_daemon_msg "Restarting ipr initialization daemon" iprinit
	stop && start
	[ "$VERBOSE" = no ] || log_end_msg $?
	;;
    status)
	if init_is_upstart; then exit 1; fi
	status
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|reload}"
	exit 1
	;;
esac
